[package]
name = "private_cdp"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.8.0"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.19.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[profile.release]
sierra-replace-ids = false
